before_script:
  - dnf install -y llvm-devel git gcc gcc-c++ make findutils diffutils gawk || (apt-get update && apt-get install -y llvm-dev git gcc g++ make findutils gawk)
  - git submodule update --init --recursive

install:fedora:
  image: fedora:latest
  script:
  - make PREFIX=/tmp/xl/ install
  - /tmp/xl/bin/xl -help

install-opt:fedora:
  image: fedora:latest
  script:
  - make PREFIX=/tmp/xl-opt/ install-opt
  - /tmp/xl-opt/bin/xl -help

install-debug:fedora:
  image: fedora:latest
  script:
  - make PREFIX=/tmp/xl-debug/ install-debug
  - /tmp/xl-debug/bin/xl -help

install-release:fedora:
  image: fedora:latest
  script:
  - make PREFIX=/tmp/xl-release/ install-release
  - /tmp/xl-release/bin/xl -help

test:fedora:
  image: fedora:latest
  script:
  - make test

test-opt:fedora:
  image: fedora:latest
  script:
  - make test-opt

test-release:fedora:
  image: fedora:latest
  script:
  - make test-release

test-debug:fedora:
  image: fedora:latest
  script:
  - make test-debug

build:fedora:
  image: fedora:latest
  script:
  - make

build-opt:fedora:
  image: fedora:latest
  script:
  - make opt

build-debug:fedora:
  image: fedora:latest
  script:
  - make opt-debug

build-release:fedora:
  image: fedora:latest
  script:
  - make opt-release

self-compile-xl2:fedora:
  image: fedora:latest
  script:
  - (cd xl2; make)

install:ubuntu:
  image: ubuntu:latest
  script:
  - make PREFIX=/tmp/xl/ install
  - /tmp/xl/bin/xl -help

install-opt:ubuntu:
  image: ubuntu:latest
  script:
  - make PREFIX=/tmp/xl-opt/ install-opt
  - /tmp/xl-opt/bin/xl -help

install-debug:ubuntu:
  image: ubuntu:latest
  script:
  - make PREFIX=/tmp/xl-debug/ install-debug
  - /tmp/xl-debug/bin/xl -help

install-release:ubuntu:
  image: ubuntu:latest
  script:
  - make PREFIX=/tmp/xl-release/ install-release
  - /tmp/xl-release/bin/xl -help

test:ubuntu:
  image: ubuntu:latest
  script:
  - make test

test-opt:ubuntu:
  image: ubuntu:latest
  script:
  - make test-opt

test-release:ubuntu:
  image: ubuntu:latest
  script:
  - make test-release

test-debug:ubuntu:
  image: ubuntu:latest
  script:
  - make test-debug

build:ubuntu:
  image: ubuntu:latest
  script:
  - make

build-opt:ubuntu:
  image: ubuntu:latest
  script:
  - make opt

build-debug:ubuntu:
  image: ubuntu:latest
  script:
  - make opt-debug

build-release:ubuntu:
  image: ubuntu:latest
  script:
  - make opt-release

self-compile-xl2:ubuntu:
  image: ubuntu:latest
  script:
  - (cd xl2; make)
